### ISSUE TITLE
No option to localize measurements.

### ISSUE THREAD

**Issue by Ep0chalypse** [Piour/piour-cozy-owm#3]
It would be great if this would localize the results, such as fahrenheit or celsius, or mm/cm or inches depending on what you have set in Settings -> Localization.

If that is too complex maybe perhaps a setting in the weather app itself to toggle localization.

**Comment by Piour** [comment]
Sorry for the very late answer, but this app is not active anymore, the new version is there : https://github.com/pierrerousseau/owm 
You can open another issue there because I think that you are right.
